config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :transactions, only: [:index, :create]
    
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"
  
  #remove transaction creation from controller
  def self.send_money sender_id, receiver_id, amount
    Transaction.create(sender_id: sender_id, receiver_id: receiver_id, amount: amount)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :sender_transactions, class_name: "Transaction", foreign_key: "sender_id"
  has_many :recevied_transactions, class_name: "Transaction", foreign_key: "receiver_id"
  after_create :add_money

  #removing bussiness logic from the controller 

  #used to seed the money for the new user
  def add_money
    Transaction.create(sender_id: nil, receiver_id: self.id, amount: 10000)
  end

  #get avaible money that can be transfered by current_user
  def get_available_money
    self.recevied_transactions.sum(:amount) - self.sender_transactions.sum(:amount)  
    # binding.pry
  end

  # can user send x amount of money 
  def amount_sendable sending_amount
    amount_available = self.get_available_money
    if amount_available > sending_amount.to_i 
      true
    else
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @users = User.where.not(id: current_user.id)
  end
end

app/controllers/transactions_controller.rb
# controller to handle all transactions
class TransactionsController < ApplicationController
  
  #forcing user to be logged in for access transactions
  before_action :authenticate_user!
  
  #to show all transactions of a user
  def index
    @transactions = Transaction.where("(sender_id = ? or receiver_id = ?)", current_user.id, current_user.id)
  end

  #create a transaction
  def create
    if !params[:amount].nil? and !params[:receiver_id].nil?
      if current_user.amount_sendable params[:amount]
        Transaction.send_money(current_user.id, params[:receiver_id], params[:amount])
        flash[:success] = "Amount Sent"
        redirect_to '/transactions'
      else
        flash[:error] = 'Not Enough Money'
        redirect_to authenticated_root_path
      end
    else
      
      flash[:error] = 'please try again'
      redirect_to authenticated_root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # removeing all model related quires from the views 
  # these methods are acting as middleware between models and views
  def get_avaiblable_money
    current_user.get_available_money
  end

  def get_user_email id
    if id == nil
      'Paytm User'
    else
      User.where(id: id).first.email
    end
  end

  def get_transaction_color id
    if current_user.id == id
      'text-success'
    else
      'text-danger'
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Paytm</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/transactions">Transactions</a>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'nav-link') %>        
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link"><span class="text-success"> $ <%= get_avaiblable_money %></span></a>
        </li>
      <% else %>
        <li class="nav-item">
        <%= link_to('Login', new_user_session_path, class: 'nav-link')  %>  
        </li> 
      <% end %>
    </ul>
    
  </div>
</nav>

app/views/home/index.html.erb
<%= render partial: 'navbar' %>

<%= flash[:notice] %>

<%= flash[:error] %>
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <h1>Avaiblable Money:    <span class="text-success"><%= get_avaiblable_money %></h1>
    </div>
    <div class="col-6 offset-3 py-5 my-5">
      <h3>Send Money</h3>
      <form action="/transactions" method="post">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
        <div class="form-group">
          <label for="exampleFormControlSelect1">Select User</label>
          <select class="form-control" name="receiver_id" required="">
            <% @users.each do |user| %>
              <option value="<%= user.id %>"><%= user.email %></option>
            <% end %>
          </select>
        </div>
        <div class="form-group">
          <label >Amount to be Sent</label>
          <input type="number" class="form-control" name="amount" required=""  >
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paytm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>

<%= yield %>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<%= render partial: 'navbar' %>
<div class="container">
  <div class="row">
    <div class="col-12 py-5 my-5">
      <h1>Recent Transactions </h1>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Sender</th>
            <th scope="col">Receiver</th>
            <th scope="col">Amount</th>
          </tr>
        </thead>
        <tbody>
          <% @transactions.each do |transaction| %>
            <tr>
              <td><%= transaction.id %></td>
              <td><%= get_user_email(transaction.sender_id) %></td>

              <td><%= get_user_email(transaction.receiver_id) %></td>
              <td class="<%= get_transaction_color(transaction.receiver_id) %>" ><%= transaction.amount %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>